USE CRUD;

DROP TABLE IF EXISTS USER;
CREATE TABLE PERSON(

  ID_PERSON INT PRIMARY KEY,
  FIRST_NAME VARCHAR(50) NOT NULL,
  SURNAME VARCHAR(50) NOT NULL,
  AGE INT NOT NULL,
  ADDRESS VARCHAR(50) NOT NULL,
  WIN VARCHAR(35) NOT NULL
);

DROP TABLE IF EXISTS CLASS;
CREATE TABLE CARS (

  ID_CARS INT PRIMARY KEY,
  CLASS VARCHAR(50) NOT NULL

);



INSERT INTO PERSON VALUES (1,'KHAWANI', 'Ahmed', 22, 'Rue Passter 76504', 'SORRY TRY AGAIN');
INSERT INTO PERSON VALUES (2,'ESSAMAMI', 'Hamza', 22, 'Rue Aristide Briand 91230', 'SORRY TRY AGAIN');
INSERT INTO PERSON VALUES (3,'LEBRUN', 'Ilona', 24, 'Rue Passteur 21345', 'SORRY TRY AGAIN');
INSERT INTO PERSON VALUES (4,'LEPEN', 'MARINE', 53, 'Rue Grand bvd', 'SORRY TRY AGAIN');
INSERT INTO PERSON VALUES (5,'MACRON', 'MANU', 47, 'Rue chabat le facho', 'SORRY TRY AGAIN');
INSERT INTO PERSON VALUES (6,'ZAIR', 'Juba', 22, 'Rue Arnold le gros 01234', 'SORRY TRY AGAIN');

INSERT INTO CARS VALUES (1,'AUDI A1');
INSERT INTO CARS VALUES (2,'AUDI A2');
INSERT INTO CARS VALUES (3,'AUDI A3');
INSERT INTO CARS VALUES (4,'AUDI A4');
INSERT INTO CARS VALUES (5,'AUDI A5');
INSERT INTO CARS VALUES (6,'AUDI A6 SLINE');
INSERT INTO CARS VALUES (7,'BMW X5');
INSERT INTO CARS VALUES (8,'BMW X1');
INSERT INTO CARS VALUES (9,'BMW X6');
