version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: CRUD
